const colors = {
  light: {
    text: '#1A0A2E',
    tint: '#FF4473',
    background: '#FDFAFF',
    foreground: '#1A0A2E',
    card: '#FFFFFF',
    cardForeground: '#1A0A2E',
    primary: '#FF4473',
    primaryForeground: '#FFFFFF',
    secondary: '#F5F0FF',
    secondaryForeground: '#1A0A2E',
    muted: '#F5F0FF',
    mutedForeground: '#7C6FA8',
    accent: '#FF4473',
    accentForeground: '#FFFFFF',
    destructive: '#ef4444',
    destructiveForeground: '#FFFFFF',
    border: '#EDE8F8',
    input: '#F5F0FF',
  },
  dark: {
    text: '#FFFFFF',
    tint: '#FF4473',
    background: '#0D0B1A',
    foreground: '#FFFFFF',
    card: '#1A1628',
    cardForeground: '#FFFFFF',
    primary: '#FF4473',
    primaryForeground: '#FFFFFF',
    secondary: '#251F40',
    secondaryForeground: '#FFFFFF',
    muted: '#251F40',
    mutedForeground: '#9385B8',
    accent: '#FF4473',
    accentForeground: '#FFFFFF',
    destructive: '#ef4444',
    destructiveForeground: '#FFFFFF',
    border: '#2E2850',
    input: '#1A1628',
  },
  radius: 16,
};

export default colors;
