kind = "mobile"
previewPath = "/"
title = "MeetSweet"
version = "1.0.0"
id = "artifacts/meetsweet"
router = "expo-domain"

[[services]]
name = "expo"
ensurePreviewReachable = "/status"
paths = [ "/" ]
localPort = 22304

[services.development]
run = "pnpm --filter @workspace/meetsweet run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/meetsweet", "run", "build" ]
run = [ "pnpm", "--filter", "@workspace/meetsweet", "run", "serve" ]

[services.env]
PORT = "22304"
BASE_PATH = "/"
