import { Router, type IRouter } from "express";
import { GetExploreCatalogResponse } from "@workspace/api-zod";

const router: IRouter = Router();

const creators = [
  {
    id: "creator-1",
    name: "Alex Rivera",
    handle: "@alex.r",
    initials: "AR",
    bio: "Visual stories from the road, one frame at a time.",
    category: "Lifestyle",
    followers: "84.2K",
    subscriberCount: 84200,
    monthlyCredits: 650,
    isVerified: true,
    isOnline: true,
    gradient: "mono-sand",
  },
  {
    id: "creator-2",
    name: "Sarah Moon",
    handle: "@sarah_m",
    initials: "SM",
    bio: "Slow living, thoughtful spaces, and everyday rituals.",
    category: "Lifestyle",
    followers: "62.8K",
    subscriberCount: 62800,
    monthlyCredits: 480,
    isVerified: true,
    isOnline: false,
    gradient: "mono-mist",
  },
  {
    id: "creator-3",
    name: "Dev Studio",
    handle: "@devstudio",
    initials: "DS",
    bio: "Clearer code, better products, and the thinking behind both.",
    category: "Tech",
    followers: "48.1K",
    subscriberCount: 48100,
    monthlyCredits: 720,
    isVerified: true,
    isOnline: true,
    gradient: "mono-slate",
  },
  {
    id: "creator-4",
    name: "Creative X",
    handle: "@creativex",
    initials: "CX",
    bio: "Art direction and visual systems for curious brands.",
    category: "Art",
    followers: "39.6K",
    subscriberCount: 39600,
    monthlyCredits: 550,
    isVerified: false,
    isOnline: true,
    gradient: "mono-ink",
  },
  {
    id: "creator-5",
    name: "Luna Kim",
    handle: "@luna.k",
    initials: "LK",
    bio: "Strength, balance, and a kinder approach to fitness.",
    category: "Fitness",
    followers: "27.4K",
    subscriberCount: 27400,
    monthlyCredits: 390,
    isVerified: true,
    isOnline: false,
    gradient: "mono-cloud",
  },
  {
    id: "creator-6",
    name: "Jay Torres",
    handle: "@jay.t",
    initials: "JT",
    bio: "Late-night loops, studio notes, and unfinished ideas.",
    category: "Music",
    followers: "19.7K",
    subscriberCount: 19700,
    monthlyCredits: 430,
    isVerified: false,
    isOnline: true,
    gradient: "mono-charcoal",
  },
  {
    id: "creator-7",
    name: "Mia Chen",
    handle: "@mia.c",
    initials: "MC",
    bio: "A field guide to beautiful places and good food.",
    category: "Travel",
    followers: "15.3K",
    subscriberCount: 15300,
    monthlyCredits: 350,
    isVerified: false,
    isOnline: true,
    gradient: "mono-stone",
  },
  {
    id: "creator-8",
    name: "Noah Vale",
    handle: "@noah.v",
    initials: "NV",
    bio: "Indie game worlds, process breakdowns, and play.",
    category: "Gaming",
    followers: "11.9K",
    subscriberCount: 11900,
    monthlyCredits: 300,
    isVerified: false,
    isOnline: false,
    gradient: "mono-fog",
  },
];

const previews = [
  { id: "preview-1", creatorId: "creator-1", title: "A week in Lisbon", category: "Lifestyle", kind: "photo", duration: "04:12", likes: "2.4K", isPremium: true, gradient: "mono-sand", lockedLabel: "650 credits" },
  { id: "preview-2", creatorId: "creator-3", title: "The calm product stack", category: "Tech", kind: "video", duration: "08:46", likes: "1.8K", isPremium: true, gradient: "mono-slate", lockedLabel: "720 credits" },
  { id: "preview-3", creatorId: "creator-4", title: "Shapes in quiet light", category: "Art", kind: "gallery", duration: "12 frames", likes: "986", isPremium: false, gradient: "mono-ink", lockedLabel: "Free preview" },
  { id: "preview-4", creatorId: "creator-6", title: "After hours / 02", category: "Music", kind: "audio", duration: "03:28", likes: "744", isPremium: true, gradient: "mono-charcoal", lockedLabel: "430 credits" },
  { id: "preview-5", creatorId: "creator-5", title: "A stronger morning", category: "Fitness", kind: "video", duration: "06:18", likes: "621", isPremium: false, gradient: "mono-cloud", lockedLabel: "Free preview" },
  { id: "preview-6", creatorId: "creator-7", title: "North coast notes", category: "Travel", kind: "photo", duration: "09 frames", likes: "512", isPremium: true, gradient: "mono-stone", lockedLabel: "350 credits" },
];

const catalog = GetExploreCatalogResponse.parse({
  creditBalance: 2450,
  categories: [
    { id: "all", label: "All", count: 128 },
    { id: "lifestyle", label: "Lifestyle", count: 34 },
    { id: "music", label: "Music", count: 18 },
    { id: "tech", label: "Tech", count: 22 },
    { id: "art", label: "Art", count: 26 },
    { id: "fitness", label: "Fitness", count: 14 },
    { id: "travel", label: "Travel", count: 9 },
    { id: "gaming", label: "Gaming", count: 5 },
  ],
  trendingSearches: ["slow living", "new creators", "exclusive", "music rooms", "visual diaries", "wellness"],
  featuredCreatorIds: ["creator-1", "creator-3", "creator-4"],
  recommendedCreatorIds: ["creator-2", "creator-5", "creator-6", "creator-7"],
  creators,
  previews,
  collections: [
    { id: "collection-1", title: "Quiet luxury", subtitle: "A slower kind of feed", itemCount: 18, gradient: "mono-sand" },
    { id: "collection-2", title: "Behind the build", subtitle: "Creators making things", itemCount: 24, gradient: "mono-slate" },
    { id: "collection-3", title: "New this week", subtitle: "Fresh voices to know", itemCount: 12, gradient: "mono-mist" },
  ],
});

router.get("/explore", (_req, res) => {
  res.json(catalog);
});

export default router;